[project]
name = "callmemaybe"
version = "0.1.0"
description = "project about function Calling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llm_sdk",
    "pydantic>=2.13.4",
]

[tool.uv.workspace]
members = ["llm_sdk"]

[tool.uv.sources]
llm_sdk = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["llm_sdk/uv_workspaces"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
