class FilterDecoder:
    """FilterDecoder class is filtring and storing static data

    Attributes:
        self.__tokens_before_prompt: encoded str before prompt
        self.__tokens_before_name: encoded str before name
        self.__tokens_before_params: encoded str before params
    """

    def __init__(self) -> None:
        """constructor Filter Decoder for constrained decoding

        Args:
            None
        Returns:
            None
        """
        self.__tokens_before_prompt: list[int] = []
        self.__tokens_before_name: list[int] = []
        self.__tokens_before_params: list[int] = []

    # setters
    def set_tokens_before_prompt(
        self, tokens_before_prompt: list[int]
    ) -> None:
        """set ids string before_prompt

        Args:
            tokens_before_prompt: list of ids key prompt
        Returns:
            None
        """
        self.__tokens_before_prompt = tokens_before_prompt

    def set_tokens_before_name(
        self, tokens_before_name: list[int]
    ) -> None:
        """set ids string before name

        Args:
            tokens_before_name: list of ids key name
        Returns:
            None
        """
        self.__tokens_before_name = tokens_before_name

    def set_tokens_before_parameters(
        self, list_before_param: list[int]
    ) -> None:
        """set ids of string before parameters

        Args:
            list_before_params: list of ids before params
        Retuns:
            None
        """
        self.__tokens_before_params = list_before_param

    # getters
    def get_tokens_before_prompt(self) -> list[int]:
        """get ids of string before prompt

        Args:
            None
        returns:
            tokens_before_prompt: list of ids before prompt
        """
        return self.__tokens_before_prompt

    def get_tokens_before_name(self) -> list[int]:
        """get ids of string before name

        Args:
            None
        returns:
            tokens_before_name: list of ids before name
        """
        return self.__tokens_before_name

    def get_tokens_before_parameters(self) -> list[int]:
        """get ids of string before parameters

        Args:
            None
        returns:
            tokens_before_params: list of ids before params
        """
        return self.__tokens_before_params

    def is_in_functions(
        self, dynamic_str: str, function_names: list[str]
    ) -> bool:
        """check if dynamic string in a function_names

        Args:
            dynamic_str: dynamic string generated by model
            function_names: function_names available
        Returns:
            bool : True if found it in function
                    otherwise return false
        """
        for function_name in function_names:
            if function_name.startswith(dynamic_str):
                return True
        return False

    def is_found_only_one_function(
        self, dynamic_generated: str, function_names: list[str]
    ) -> bool:
        """check if dynamic string starts in one function
              not more in function names

        Args:
            dynamic_generated: dynamic generated by model
            function_names: available functions
        Returns:
            bool: True if found only one function
                    otherwise return False
        """
        counter = 0
        for function_name in function_names:
            if function_name.startswith(dynamic_generated):
                counter += 1
        if counter == 1:
            return True
        return False

    def is_closed_brackets(self, json_str: str) -> bool:
        """check if is closed brackets in generated json

        Args:
            json_str: generated json by model
        Returns:
            bool if is closed return True
                otherwise Returns False"""
        counter_quotes = 0
        counter_brackets = 0
        for char in json_str:
            if char == "\"":
                counter_quotes += 1
            if not (counter_quotes % 2) and char == '{':
                counter_brackets += 1
            elif not (counter_quotes % 2) and char == '}':
                counter_brackets -= 1
        return counter_brackets == 0
